image: registry.gitlab.com/danubetech/devops/docker-maven-danubetech:latest

stages:
  - build
  - test

build:
  stage: build
  script:
    - wget https://github.com/dcdpr/libbech32-java/archive/master.zip && unzip master.zip && cd libbech32-java-master && mvn install -DskipTests=true && cd .. && rm master.zip 
    - wget https://github.com/dcdpr/libtxref-java/archive/master.zip && unzip master.zip && cd libtxref-java-master && mvn install -DskipTests=true && cd .. && rm master.zip 
    - mvn compile